# Generated by Django 5.2.3 on 2025-07-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_staff_student_remove_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
