# Generated by Django 5.2.3 on 2025-07-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_staff_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_available',
        ),
        migrations.AddField(
            model_name='service',
            name='department',
            field=models.CharField(choices=[('SCES Helpdesk', 'SCES Helpdesk'), ('Administration', 'Administration'), ('Lecturer Consultation', 'Lecturer Consultation')], default='123', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('unavailable', 'Unavailable')], default='123', max_length=20),
            preserve_default=False,
        ),
    ]
